### ISSUE TITLE
how to bundle all js with webpack into a js file?

### ISSUE THREAD

**Issue by xiaohan2013** [JeremyMorgan/Angular-Kickstart#6]
@JeremyMorgan  hello! now i want to concat all js file with webpack, but in the browser will emit error

`Uncaught Error: [$injector:modulerr] Failed to instantiate module angularstrapApp due to:
Error: [$injector:nomod] Module 'angularstrapApp' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.0-build.3042+sha.76e57a7/$injector/nomod?p0=angularstrapApp
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:104:12
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:199:17
    at ensure (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:123:38)
    at module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:197:14)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1023:31)
    at angular.module (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1173:38)
    at http://localhost:8080/assets/app.bundle.js:4713:23
    at forEach (http://localhost:8080/assets/app.bundle.js:417:21)
    at loadModules (http://localhost:8080/assets/app.bundle.js:4697:6)
    at createInjector (http://localhost:8080/assets/app.bundle.js:4619:20)
http://errors.angularjs.org/1.5.8/$injector/modulerr?p0=angularstrapApp&p1=…ctor%20(http%3A%2F%2Flocalhost%3A8080%2Fassets%2Fapp.bundle.js%3A4619%3A20)`

Please help me,Thank you very much.

**Comment by JeremyMorgan** [comment]
I'll look into this. It likely has to do with a file path issue I'm working with.
